kafka:
  brokers:
    - broker:29092
  schemaRegistry:
    enabled: true
    urls: ["http://schema-registry:18081"]

connect:
  enabled: true
  clusters:
    - name: connect
      url: http://connect:18083

# server:
#  listenPort: 8080