server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      force: true


keycloak:
  auth-server-url: https://localhost:4443/
  realm: spring-test-app
  resource: spring-test-app-client
  public-client: true


