server:
  port: 8080
  servlet:
    encoding:
      enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

client:
  test-feign: http://localhost:4999

keycloak:
  auth-server-url: https://localhost:4443
  realm: spring-test-app
  resource: spring-test-app-client
  public-client: true
  disable-trust-manager: true


