version: '3.8'

networks:
  spring-test-network:
    external: true

services:
  vector-dev:
    image: timberio/vector:0.23.0-alpine
    container_name: vector-dev
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
      - ./log/:/tmp/
    networks:
      - spring-test-network
    ports:
      - 24224:24224

  config-server:
    container_name: config-server
    build:
      context: ../config-server
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        tag: config-server.logs
        fluentd-async-connect: 'true'
    volumes:
      -  ../config-server/config:/config
    networks:
      - spring-test-network
    ports:
      - 4071:8071

  postgres-db:
    container_name: postgres-db
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data:Z
      - ./backup:/home/backup:rw
    environment:
      POSTGRES_DB: spring-test-app-db
      POSTGRES_USER: spring-test-app
      POSTGRES_PASSWORD: 82dbe72b-2684-4888-a509-b119a9c613bf
      PGDATA: /var/lib/postgresql/data/spring-test-app-data
    networks:
      - spring-test-network
    ports:
      - 4432:5432

  keycloak:
    container_name: keycloak
    build:
      context: ../keycloak
    environment:
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/spring-test-app-db
      KC_DB_USERNAME: spring-test-app
      KC_DB_PASSWORD: 82dbe72b-2684-4888-a509-b119a9c613bf
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost:4443
      KC_PROXY: passthrough
    networks:
      - spring-test-network
    ports:
      - 4443:8443
    depends_on:
      - postgres-db

  sprint-test-app:
    container_name: sprint-test-app
    build:
      context: ../app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        tag: app.logs
        fluentd-async-connect: 'true'
    networks:
      - spring-test-network
    ports:
      - 8080:8080
    depends_on:
      - config-server

  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock
    command: --local-response-templating --verbose
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        tag: wiremock.logs
        fluentd-async-connect: 'true'
    volumes:
      - ../wiremock/data:/home/wiremock:ro
    networks:
      - spring-test-network
    ports:
      - 4999:8080
