# Set global options
[sources.spring-test]
type = "fluent"
address = "0.0.0.0:24224"

[sinks.file]
type = "file"
inputs = [ "spring-test" ]
compression = "none"
path = "/tmp/service-%Y-%m-%d.log"

[sinks.file.encoding]
codec = "json"

[sinks.my_sink_id]
type = "console"
inputs = [ "spring-test" ]
target = "stdout"

[sinks.my_sink_id.encoding]
codec = "json"
