server:
  port: 8072

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        #enable auto discovery
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include:
          - gateway
