server:
  port: 8080
  servlet:
    encoding:
      enabled: true

spring:
  application:
    name: spring-test-app
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  config:
    import: optional:configserver:http://localhost:8071

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring-test-app:
  editable-value: init-value
  client:
    test-feign: http://localhost:4999
  kafka:
    enabled: false
    bootstrap-address: localhost:9092
    topic: "spring-test-app-topic"
    group-id: fddf7f06-d04c-4efd-9cad-723ca7697a63


keycloak:
  auth-server-url: https://localhost:8443
  realm: spring-test-app
  resource: spring-test-app-client
  public-client: true
  disable-trust-manager: true

