server:
  port: 8080
  servlet:
    encoding:
      enabled: true

spring:
  application:
    name: app
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      app-support-call:
        register-health-indicator: true
        sliding-window-size: 3
        sliding-window-type: count_based
        # время, которое размыкатель должен ждать перед переходом из разомкнутого состояния в полуоткрытое.
        wait-duration-in-open-state: 30s
        # Порог частоты отказов в %. Когда частота отказов оказывается больше или равна этому порогу,
        # размыкатель переходит в разомкнутое состояние и начинает отвергать вызовы
        failure-rate-threshold: 50
        # исключение которые должны расцениваться как сбои
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException

feign:
  circuitbreaker:
    enabled: true

spring-test-app:
  editable-value: init-value
  client:
    test-feign: #http://localhost:4999
    app-support: app-support
  kafka:
    enabled: false
    bootstrap-address: #localhost:9092
    topic: "spring-test-app-topic"
    group-id: fddf7f06-d04c-4efd-9cad-723ca7697a63

keycloak:
  auth-server-url: #https://localhost:8443
  realm: spring-test-app
  resource: spring-test-app-client
  public-client: true
  disable-trust-manager: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
