server:
  servlet:
    encoding:
      enabled: true

spring:
  application:
    name: app-support
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    inetutils:
      default-hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
