server:
  port: 8071

spring:
  application:
    name: spring-test-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/project/java/spring-test/infrastructure/config-server/config

management:
  endpoints:
    web:
      exposure:
        include: "*"
